# ================================================================
# 0. Section: IMPORTS
# ================================================================
import csv
import pathlib
import types
from dataclasses import dataclass
import numpy as np
import mujoco
from .quaternions import (
    mujoco_to_numpy_quaternion,
    numpy_to_mujoco_quaternion,
    quat_mul,
    quat_inv,
    quat_rotate,
)

_PARAMS_PATH = pathlib.Path(__file__).parent.parent / "params" / "wind_fit_params.csv"


def _load_fit_params(path: pathlib.Path) -> types.SimpleNamespace:
    """Load wind surface-fit parameters from CSV and return them with dot-access.

    Returns a SimpleNamespace so params can be accessed as:
        params.l_qx.A, params.l_qy.phi_rad, params.r_qx.bias, ...
    """
    rows = {}
    with open(path) as f:
        for row in csv.DictReader(f):
            rows[row["component"]] = types.SimpleNamespace(
                A=float(row["A"]),
                phi_rad=float(row["phi_deg"]) * np.pi / 180,
                bias=float(row["bias"]),
            )
    return types.SimpleNamespace(**rows)


# ================================================================
# 1. Section: Wind Class
# ================================================================
@dataclass
class Wind:
    def __init__(self, model: mujoco.MjModel) -> None:
        """Cache rest-pose antenna geometry needed to compute wind-driven deflections.

        The pedicel (fixed, no joints) sits between the funiculus and the thorax in
        the kinematic chain, so its rest quaternion is stored to transform funiculus
        deflections into the fly's egocentric frame.

        Args:
            model: MuJoCo model object exposing body_pos and body_quat accessors.
        """
        # self.funiculus_position_0 = [
        #     model.body_pos[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "funiculus_l")],
        #     model.body_pos[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "funiculus_r")],
        # ]
        # self.pedicel_angle_0 = [
        #     model.body_quat[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "pedicel_l")],
        #     model.body_quat[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "pedicel_r")],
        # ]
        self.fit_params = _load_fit_params(_PARAMS_PATH)
        self.wind_signal = []
        self.estimated_wind_angles = []
        self.norm_qpos_history = []
        self.current_signal = None
        self.current_estimated_wind_angle = None
        # Warm-up gate: the antenna starts from rest at simulation start and needs
        # ~400 steps to settle before the arctan2 estimate is reliable.

    def add_signal(self, signal: np.ndarray) -> None:
        """Store the generated control signal in the `wind_signal` property.
        Args:
            signal: (np.ndarray) 2 dimensional vector with the left and right drives generated by the wind."""
        self.wind_signal.append(signal)

    def add_angle(self, angle: float) -> None:
        """Store the estimated wind angle in the `wind_angle` property.
        Args:
            angle: (float) Estimated wind angle in radians."""
        self.estimated_wind_angles.append(angle)

    def add_norm_qpos_history(self, qpos: list[np.ndarray]) -> None:
        """Store the scale-corrected antenna qpos in the `norm_qpos_history` property for smoothing."""
        self.norm_qpos_history.append(qpos)

    def _correct_scale_and_bias(self, antenna_data: list[np.ndarray]) -> list[np.ndarray]:
        """Apply the fit correction to each antenna's signals. Brings f = k * magnitude * sin(theta + phi) + bias to the form f = magnitude * sin(theta + phi)."""
        l_qx_corrected = (antenna_data['l']['qpos'][1] - self.fit_params.l_qx.bias) / self.fit_params.l_qx.A
        l_qy_corrected = (antenna_data['l']['qpos'][2] - self.fit_params.l_qy.bias) / self.fit_params.l_qy.A
        r_qx_corrected = (antenna_data['r']['qpos'][1] - self.fit_params.r_qx.bias) / self.fit_params.r_qx.A
        r_qy_corrected = (antenna_data['r']['qpos'][2] - self.fit_params.r_qy.bias) / self.fit_params.r_qy.A
        return [l_qx_corrected, l_qy_corrected, r_qx_corrected, r_qy_corrected]

    def _compute_magnitude(self, scale_corrected_data: list[np.ndarray]) -> float:
        """Compute wind magnitude from the corrected antenna signals. Uses the fit parameters to estimate the magnitude."""
        l_magnitude = np.sqrt(scale_corrected_data[0]**2 + scale_corrected_data[1]**2)
        r_magnitude = np.sqrt(scale_corrected_data[2]**2 + scale_corrected_data[3]**2)
        estimated_magnitude = (l_magnitude + r_magnitude) / 2  # Average of both antennas
        return estimated_magnitude
    
    def _correct_phase(self, qpos_processed: list) -> list[np.ndarray]:
        # This step might not be needed
        pass

    def _compute_angle(self, scale_corrected_data: list[np.ndarray]) -> float:
        l_angle = np.arctan2(scale_corrected_data[0], scale_corrected_data[1])  # atan2(qx, qy)
        r_angle = np.arctan2(scale_corrected_data[2], scale_corrected_data[3])  # atan2(qx, qy)
        # Circular mean: arithmetic average breaks at the ±π discontinuity when the
        # two antennas land on opposite sides (e.g. +173° and -172° average to 0°).
        estimated_angle = np.angle(np.exp(1j * l_angle) + np.exp(1j * r_angle))
        self.current_estimated_wind_angle = estimated_angle
        return estimated_angle
    
    def _smooth_signals(self, signal: list[np.ndarray], win: int = 200) -> list[np.ndarray]:
        """Apply exponential smoothing to the corrected antenna signals."""
        if len(self.norm_qpos_history) < win - 1:
            return signal
        else:
            win_signals = np.array(self.norm_qpos_history[-(win - 1):] + [signal])  # Shape (win, 4)
            smoothed_signal = np.mean(win_signals, axis=0)  # Shape (4,)
            return smoothed_signal

    def _generate_control_signal(
        self,
        wind_angle: float,
        bias: float = 0,
        lat_k: float = 1,
        fwd_k: float = 1,
    ) -> np.ndarray:
        """Convert egocentric antenna deflections into a [left, right] motor drive signal.

        Lateral (y-axis) deflection difference steers the fly; forward (x-axis) deflection
        sum scales both sides to produce upwind thrust. The signal is inverted so the fly
        turns toward the wind source.

        Args:
            egocentric_deflection: List[np.ndarray] of [left, right] deflection vectors in
                the fly's frame, each of shape (3,).
            bias: Additive offset applied to both channels (default 0).
            lat_k: Gain on the lateral (steering) component (default 1).
            fwd_k: Gain on the forward (thrust) component (default 1).

        Returns:
            np.ndarray: Shape (2,) array of [left_drive, right_drive].
        """
        drive_angle = wind_angle + np.pi  # Invert angle to turn toward the wind
        forward_component = fwd_k * np.cos(drive_angle) * np.ones(2)  
        lateral_component = lat_k * np.sin(drive_angle)
        if lateral_component > 0:
            lateral_component_v = np.array([lateral_component, 0])
        else:
            lateral_component_v = np.array([0, lateral_component])

        control_signal = forward_component + lateral_component_v

        self.add_signal(control_signal)
        
        return control_signal
    
    def process_wind(
        self,
        antenna_data: dict[str, dict[str, np.ndarray]],
        bias: float = 0,
        lat_k: float = 0,
        fwd_k: float = 0,
    ) -> np.ndarray:
        """Run the full wind-sensing pipeline and return a motor drive signal.

        Chains funiculus position estimation, deflection computation, egocentric
        transformation, and control signal generation.

        Args:
            antenna_data: Dict with keys "l" and "r", each containing a "qpos" quaternion
                for the current antenna joint orientation.

        Returns:
            np.ndarray: Shape (2,) array of [left_drive, right_drive].
        """

        scaled_signals = self._correct_scale_and_bias(antenna_data)
        self.add_norm_qpos_history(scaled_signals)
        smoothed_signals = self._smooth_signals(scaled_signals)
        angle = self._compute_angle(smoothed_signals)
        self.add_angle(angle)
        control_signal = self._generate_control_signal(angle, bias=bias, lat_k=lat_k, fwd_k=fwd_k)
        self.current_signal = control_signal

        return control_signal
