# ================================================================
# 0. Section: IMPORTS
# ================================================================
import csv
import pathlib
import types
from dataclasses import dataclass
import numpy as np
import mujoco
from .quaternions import (
    mujoco_to_numpy_quaternion,
    numpy_to_mujoco_quaternion,
    quat_mul,
    quat_inv,
    quat_rotate,
)

_PARAMS_PATH = (
    pathlib.Path(__file__).parent.parent
    / "periphery"
    / "params"
    / "wind_fit_params.csv"
)


def _load_fit_params(path: pathlib.Path) -> types.SimpleNamespace:
    """Load wind surface-fit parameters from CSV and return them with dot-access.

    Returns a SimpleNamespace so params can be accessed as:
        params.l_qx.A, params.l_qy.phi_rad, params.r_qx.bias, ...
    """
    rows = {}
    with open(path) as f:
        for row in csv.DictReader(f):
            rows[row["component"]] = types.SimpleNamespace(
                A=float(row["A"]),
                phi_rad=float(row["phi_deg"]) * np.pi / 180,
                bias=float(row["bias"]),
            )
    return types.SimpleNamespace(**rows)


# ================================================================
# 1. Section: Wind Class
# ================================================================
@dataclass
class Wind:
    def __init__(self, model: mujoco.MjModel, config: dict) -> None:
        """Cache rest-pose antenna geometry needed to compute wind-driven deflections.

        The pedicel (fixed, no joints) sits between the funiculus and the thorax in
        the kinematic chain, so its rest quaternion is stored to transform funiculus
        deflections into the fly's egocentric frame.

        Args:
            model: MuJoCo model object exposing body_pos and body_quat accessors.
            config: Dictionary containing wind-related configuration parameters.
        """
        self.fit_params = _load_fit_params(_PARAMS_PATH)
        self.wind_signal = []
        self.estimated_wind_angles = []
        self.norm_qpos_history = []
        self.current_signal = None
        self.current_estimated_wind_angle = None

        self.fwd_k = config["fwd_k"]
        self.lat_k = config["lat_k"]
        self.fnulling_threshold = config["fnulling_threshold"]
        self.qacc_threshold = config["qacc_threshold"]

    def add_signal(self, signal: np.ndarray) -> None:
        """Store the generated control signal in the `wind_signal` property.
        Args:
            signal: (np.ndarray) 2 dimensional vector with the left and right drives generated by the wind.
        """
        self.wind_signal.append(signal)

    def add_angle(self, angle: float) -> None:
        """Store the estimated wind angle in the `wind_angle` property.
        Args:
            angle: (float) Estimated wind angle in radians."""
        self.estimated_wind_angles.append(angle)

    def add_norm_qpos_history(self, qpos: list[np.ndarray]) -> None:
        """Store the scale-corrected antenna qpos in the `norm_qpos_history` property for smoothing."""
        self.norm_qpos_history.append(qpos)

    def _correct_scale_and_bias(
        self, antenna_data: list[np.ndarray]
    ) -> list[np.ndarray]:
        """Apply the fit correction to each antenna's signals. Brings f = k * magnitude * sin(theta + phi) + bias to the form f = magnitude * sin(theta + phi)."""
        l_qx_corrected = (
            antenna_data["l"]["qpos"][1] - self.fit_params.l_qx.bias
        ) / self.fit_params.l_qx.A
        l_qy_corrected = (
            antenna_data["l"]["qpos"][2] - self.fit_params.l_qy.bias
        ) / self.fit_params.l_qy.A
        r_qx_corrected = (
            antenna_data["r"]["qpos"][1] - self.fit_params.r_qx.bias
        ) / self.fit_params.r_qx.A
        r_qy_corrected = (
            antenna_data["r"]["qpos"][2] - self.fit_params.r_qy.bias
        ) / self.fit_params.r_qy.A
        return [l_qx_corrected, l_qy_corrected, r_qx_corrected, r_qy_corrected]

    def _compute_magnitude(self, phase_corrected: tuple) -> float:
        """Compute wind magnitude from phase-corrected (sin, cos) pairs.

        Each antenna yields (magnitude·sin, magnitude·cos) after phase correction,
        so the Euclidean norm is exactly the wind magnitude.
        """
        l_sin, l_cos, r_sin, r_cos = phase_corrected
        l_magnitude = np.sqrt(l_sin**2 + l_cos**2)
        r_magnitude = np.sqrt(r_sin**2 + r_cos**2)
        return (l_magnitude + r_magnitude) / 2

    def _correct_phase(self, scaled_signals: list) -> tuple:
        """Rotate each antenna's (qx, qy) pair into a true (sin, cos) quadrature pair.

        After bias/scale correction each channel is magnitude·sin(angle + φ).
        We solve the 2×2 linear system
            [s1]   [cos φ1  sin φ1] [magnitude·sin(angle)]
            [s2] = [cos φ2  sin φ2] [magnitude·cos(angle)]
        whose inverse is
            [sin(angle)]   1/det · [ sin φ2  -sin φ1] [s1]
            [cos(angle)] =         [-cos φ2   cos φ1] [s2]
        with det = sin(φ2 − φ1).

        This gives an exact (sin, cos) pair regardless of the individual φ offsets,
        as long as the two channels are not in phase (det ≠ 0).
        """
        l_qx, l_qy, r_qx, r_qy = scaled_signals

        phi1 = self.fit_params.l_qx.phi_rad
        phi2 = self.fit_params.l_qy.phi_rad
        det = np.sin(phi2 - phi1)
        l_sin = (np.sin(phi2) * l_qx - np.sin(phi1) * l_qy) / det
        l_cos = (-np.cos(phi2) * l_qx + np.cos(phi1) * l_qy) / det

        phi1 = self.fit_params.r_qx.phi_rad
        phi2 = self.fit_params.r_qy.phi_rad
        det = np.sin(phi2 - phi1)
        r_sin = (np.sin(phi2) * r_qx - np.sin(phi1) * r_qy) / det
        r_cos = (-np.cos(phi2) * r_qx + np.cos(phi1) * r_qy) / det

        return l_sin, l_cos, r_sin, r_cos

    def _compute_angle(self, phase_corrected: tuple) -> float:
        l_sin, l_cos, r_sin, r_cos = phase_corrected
        l_angle = np.arctan2(l_sin, l_cos)
        r_angle = np.arctan2(r_sin, r_cos)
        # Circular mean: arithmetic average breaks at the ±π discontinuity when the
        # two antennas land on opposite sides (e.g. +173° and -172° average to 0°).
        estimated_angle = np.angle(np.exp(1j * l_angle) + np.exp(1j * r_angle))
        self.current_estimated_wind_angle = estimated_angle
        return estimated_angle

    def _compute_adhesion(self, wind_angle: float) -> np.ndarray:
        """Compute an adhesion signal based on the wind angle. For example, full adhesion when wind is from the sides."""
        return np.array([1, 1, 1, 1, 1, 1])  # Full adhesion when wind is from the sides
        
    def _smooth_signals(
        self, signal: list[np.ndarray], win: int = 200
    ) -> list[np.ndarray]:
        """Apply exponential smoothing to the corrected antenna signals."""
        if len(self.norm_qpos_history) < win - 1:
            return signal
        else:
            win_signals = np.array(
                self.norm_qpos_history[-(win - 1) :] + [signal]
            )  # Shape (win, 4)
            smoothed_signal = np.mean(win_signals, axis=0)  # Shape (4,)
            return smoothed_signal

    def _generate_control_signal(
        self,
        wind_angle: float,
        scaler: float = 1,
    ) -> np.ndarray:
        """Convert egocentric antenna deflections into a [left, right] motor drive signal.

        Lateral (y-axis) deflection difference steers the fly; forward (x-axis) deflection
        sum scales both sides to produce upwind thrust. The signal is inverted so the fly
        turns toward the wind source.

        Args:
            egocentric_deflection: List[np.ndarray] of [left, right] deflection vectors in
                the fly's frame, each of shape (3,).
            bias: Additive offset applied to both channels (default 0).
            scaler: Scaling factor for the control signal (default 1).

        Returns:
            np.ndarray: Shape (2,) array of [left_drive, right_drive].
        """
        adhesion = None
        forward_component = self.fwd_k * np.cos(wind_angle)
        lateral_component = self.lat_k * np.sin(wind_angle)
        control_signal = np.array([forward_component, lateral_component]) * scaler
        self.add_signal(control_signal)
        adhesion = self._compute_adhesion(wind_angle)

        if np.abs(wind_angle) < np.radians(30) or np.abs(wind_angle) > np.radians(150):
            control_signal = np.array([0, 0])  # No drive when wind is from the front or back

        return control_signal, adhesion

    def process_wind(
        self,
        antenna_data: dict[str, dict[str, np.ndarray]],
        magnitude_threshold: float = 50_000,
    ) -> np.ndarray:
        """Run the full wind-sensing pipeline and return a motor drive signal.

        Chains funiculus position estimation, deflection computation, egocentric
        transformation, and control signal generation.

        Args:
            antenna_data: Dict with keys "l" and "r", each containing a "qpos" quaternion
                for the current antenna joint orientation.

        Returns:
            np.ndarray: Shape (2,) array of [left_drive, right_drive].
        """
        scaled_signals = self._correct_scale_and_bias(antenna_data)
        self.add_norm_qpos_history(scaled_signals)
        # smoothed_signals = self._smooth_signals(scaled_signals, 1)
        phase_corrected = self._correct_phase(scaled_signals)
        angle = self._compute_angle(phase_corrected)
        magnitude = self._compute_magnitude(phase_corrected)
        if magnitude < magnitude_threshold:
            scaler = 0
        else:
            scaler = 1
        self.add_angle(angle)
        control_signal, adhesion = self._generate_control_signal(
            angle, scaler=scaler
        )
        self.current_signal = control_signal

        max_qacc = max(
            np.max(np.abs(antenna_data["l"]["qacc"])),
            np.max(np.abs(antenna_data["r"]["qacc"])),
        )
        if max_qacc > self.qacc_threshold:
            adhesion = np.ones(6)

        return control_signal, adhesion
