controller:
  base_vf: 10
  max_vt: 7
  dropoff_vt: 1.86

olfaction:
  gain: 5

vision:
   min_height: 200
   scare_height: 300
   gain: 5
   slow_down_rate: 0.5
   alpha: 0.1

# "leg pos": (Coxa, Coxa_roll, Coxa_yaw, Femur, Femur_roll, Tibia, Tarsus1)
hybrid_max_increment: 80.0
hybrid:
  f:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: -0.00085
    femur_lift: 0.02592
    femur_roll: 0.0
    tibia_lift: -0.02022
    tarsus1_lift: -0.00198
  m:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: -0.00482
    femur_lift: -0.01554
    femur_roll: 0.0
    tibia_lift: 0.02811
    tarsus1_lift: 0.01727
  h:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: -0.01263
    femur_lift: 0.02018
    femur_roll: 0.0
    tibia_lift: 0.01973
    tarsus1_lift: -0.00163
