controller:
  base_vf: 15
  max_vt: 7
  dropoff_vt: 1.86

olfaction:
  gain: 5

vision:
   min_height: 200
   scare_height: 350
   gain: 2
   slow_down_rate: 0.8
   alpha: 0.05

# "leg pos": (Coxa, Coxa_roll, Coxa_yaw, Femur, Femur_roll, Tibia, Tarsus1)
hybrid_max_increment: 80.0
hybrid:
  f:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: 0.0
    femur_lift: 0.0
    femur_roll: 0.0
    tibia_lift: 0.0
    tarsus1_lift: 0.0
  m:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: 0.0
    femur_lift: 0.0
    femur_roll: 0.0
    tibia_lift: 0.0
    tarsus1_lift: 0.0
  h:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: 0.0
    femur_lift: 0.0
    femur_roll: 0.0
    tibia_lift: 0.0
    tarsus1_lift: 0.0
