name: "stable_no_hybrid_10"
controller:
  base_vf: 10
  max_vt: 7
  dropoff_vt: 3

olfaction:
  gain: 5

vision:
  min_height: 200
  scare_height: 405
  gain: 2.5
  slow_down_rate: 0.2
  alpha: 0.5
  leaf_hue: 120
  leaf_saturation: 0.95
  leaf_value: 0.875
  tolerance_hue: 5
  tolerance_value: 12.5
  tolerance_saturation: 5

# "leg pos": (Coxa, Coxa_roll, Coxa_yaw, Femur, Femur_roll, Tibia, Tarsus1)
hybrid_max_increment: 80.0
hybrid:
  f:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: 0.0
    femur_lift: 0.0
    femur_roll: 0.0
    tibia_lift: 0.0
    tarsus1_lift: 0.0
  m:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: 0.0
    femur_lift: 0.0
    femur_roll: 0.0
    tibia_lift: 0.0
    tarsus1_lift: 0.0
  h:
    coxa_lift: 0.0
    coxa_roll: 0.0
    coxa_yaw: 0.0
    femur_lift: 0.0
    femur_roll: 0.0
    tibia_lift: 0.0
    tarsus1_lift: 0.0
